### ISSUE TITLE
Provide an option to always render the startup time in seconds

### ISSUE THREAD

**Issue by yphus** [canonical/etrace#43]
Having to post process output like `Total startup time: 1m10.027260157s` is not great.
Would be really helpful to either provide an option to specify the time unit or force the time to always be returned in seconds.

e.g:

`fmt.Fprintln(w, "Total startup time:", startup.Seconds())`

**Comment by anonymouse64** [comment]
This should be relatively harmless to change this, but also note that if you are parsing this, the JSON output is really meant more for machine consumption:

```
etrace -j exec -t -s --cmd-stderr=/dev/null --cmd-stdout=/dev/null chromium  | jq
{
  "Runs": [
    {
      "ExecveTiming": null,
      "TimeToDisplay": 3561795657,
      "TimeToRun": 3561795657,
      "Errors": null
    }
  ]
}
```

The "Total startup time" corresponds to `TimeToDisplay` item in the JSON output, and is always in nanoseconds.
